# Generated by Django 3.1.2 on 2021-01-19 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mlpart', '0011_auto_20210118_2058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fileok',
            options={'ordering': ['id']},
        ),
    ]
