# Generated by Django 3.1.2 on 2021-01-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlpart', '0013_endpoint_mlalgorithm_mlalgorithmstatus_mlrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='approvals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
