# Generated by Django 3.1.2 on 2021-02-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlpart', '0014_approvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvals',
            name='Applicantincome',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='Area',
            field=models.CharField(choices=[('Rural', 'Rural'), ('Semiurban', 'Semiurban'), ('Urban', 'Urban')], default='Rural', max_length=15),
        ),
        migrations.AddField(
            model_name='approvals',
            name='Coapplicatincome',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='Credithistory',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='Dependants',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='Firstname',
            field=models.CharField(default='John', max_length=15),
        ),
        migrations.AddField(
            model_name='approvals',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=15),
        ),
        migrations.AddField(
            model_name='approvals',
            name='Graduatededucation',
            field=models.CharField(choices=[('Graduate', 'Graduated'), ('Not_Graduate', 'Not_Graduate')], default='Graduated', max_length=15),
        ),
        migrations.AddField(
            model_name='approvals',
            name='Lastname',
            field=models.CharField(default='Doe', max_length=15),
        ),
        migrations.AddField(
            model_name='approvals',
            name='Loanamt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='Loanterm',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='approvals',
            name='Married',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=15),
        ),
        migrations.AddField(
            model_name='approvals',
            name='Selfemployed',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=15),
        ),
    ]
