# Generated by Django 3.1.2 on 2021-02-17 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mlpart', '0015_auto_20210201_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLmodel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mlmodel', models.FileField(upload_to='')),
                ('name', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='MlmodelData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.FileField(max_length=225, upload_to='')),
                ('model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlpart.mlmodel')),
            ],
        ),
    ]
