# Generated by Django 3.1.2 on 2021-02-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlpart', '0016_mlmodel_mlmodeldata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileok',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
