# Generated by Django 3.1.2 on 2021-02-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlpart', '0017_auto_20210218_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileok',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
