# Generated by Django 3.1.2 on 2021-02-18 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mlpart', '0018_auto_20210218_0852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mlmodeldata',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='mlmodeldata',
            name='model_id',
        ),
        migrations.AddField(
            model_name='mlmodeldata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mlmodeldata',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mlmodeldata',
            name='data',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='mlmodeldata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='MLmodel',
        ),
    ]
