# Generated by Django 3.1.2 on 2021-02-19 15:29

from django.db import migrations, models
import mlpart.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mlpart', '0020_auto_20210219_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileok',
            name='file',
            field=models.FileField(upload_to='', validators=[mlpart.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='mlmodeldata',
            name='data',
            field=models.FileField(upload_to=''),
        ),
    ]
